### ISSUE TITLE
Resource Table Bug

### ISSUE THREAD

**Issue by Sensei412** [NX-Editor/NX-Editor#29]
Editing the RSTB on 0.3.5 cause an infinite loading screen on TOTK. Using 0.3.1 to redo the changes to the RSTB fixed my mod. Attaching my mods, both the old and the fixed version
[OPElementalSetPiecesOLD.zip](https://github.com/NX-Editor/NX-Editor/files/11670718/OPElementalSetPiecesOLD.zip)
[OPElementalSetPiecesFIXED.zip](https://github.com/NX-Editor/NX-Editor/files/11670725/OPElementalSetPiecesFIXED.zip)

**Comment by ArchLeaders** [comment]
Seems to be an issue with the hash table and serializer. Currently reworking the RESTBL editor now to hopefully fix the issue.

**Comment by ArchLeaders** [comment]
The new editor will remove the *Tears of the Kingdom* hash table to support other games and hopefully avoid hashing issues.

This will make searching keys more difficult because they will need to be exact matches, however I intend to implement something to load a custom hash table to support a more verbose search action in a later release.

**Comment by ArchLeaders** [comment]
Should be resolved by https://github.com/NX-Editor/NX-Editor/commit/35d6224b615c4f38caafd939550cb00fde4b35cd, just need to test it.

**Comment by ArchLeaders** [comment]
Seems to be fixed in `0.3.6`, closing this issue as completed. Feel free to re-open if you're still having issues with the latest version.
